import Header from '@/components/pages/layout/Header'
import './globals.css'
import Footer from '@/components/pages/layout/Footer'
import { TailwindIndicator } from '@/components/tailwind-indicator'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
                <Footer />
                <TailwindIndicator />
            </body>
        </html>
    )
}
