import type { Metadata } from "next";
import "../styles/globals.css";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const roboto = Roboto({
   weight: ["400", "700", "100", "300", "400", "500", "900"],
   style: ["normal", "italic"],
   subsets: ["latin"],
   display: "swap",
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${roboto.className} antialiased bg-slate-50`}>{children}</body>
      </html>
   );
}
